builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    flags:
      - -tags=osusergo,netgo
    ldflags:
      - -s -w -X main.version={{.Version}}
    hooks:
      post: |
        upx -q --best --lzma "{{ .Path }}"
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: simonswine
    name: mi-flora-exporter
